version: "3.1"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: boxgame
      POSTGRES_USER: boxgame
      POSTGRES_DB: boxgame
    ports:
      - 5432:5432
