// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CommentLikeInput struct {
	CommentID string `json:"commentId"`
	UserID    string `json:"userId"`
}

type NewAddress struct {
	City       string  `json:"city"`
	Line1      string  `json:"line1"`
	Line2      *string `json:"line2"`
	State      string  `json:"state"`
	Country    string  `json:"country"`
	PostalCode string  `json:"postalCode"`
}

type NewBattlegroundRoom struct {
	TeamIds []string `json:"teamIds"`
}

type NewComment struct {
	Content string `json:"content"`
	PostID  string `json:"postId"`
	UserID  string `json:"userId"`
}

type NewInvitation struct {
	From   string `json:"from"`
	To     string `json:"to"`
	TeamID string `json:"teamId"`
}

type NewPost struct {
	Content string   `json:"content"`
	Images  []string `json:"images"`
	UserID  string   `json:"userId"`
}

type NewProfile struct {
	Status        *PastoralStatus `json:"status"`
	Gender        Gender          `json:"gender"`
	Satellite     *Satellite      `json:"satellite"`
	NameEng       string          `json:"nameEng"`
	NameChi       *string         `json:"nameChi"`
	Contact       string          `json:"contact"`
	Dob           time.Time       `json:"dob"`
	TngReceiptURL *string         `json:"tngReceiptUrl"`
	AvatarURL     *string         `json:"avatarUrl"`
	Address       *NewAddress     `json:"address"`
	InvitedBy     *string         `json:"invitedBy"`
}

type NewTeam struct {
	Name      string  `json:"name"`
	AvatarURL *string `json:"avatarUrl"`
	ClusterID *string `json:"clusterId"`
}

type NewUser struct {
	ID       *string     `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Profile  *NewProfile `json:"profile"`
	Roles    []Role      `json:"roles"`
	TeamID   *string     `json:"teamId"`
}

type PaginationInput struct {
	Offset int `json:"offset"`
	Limit  int `json:"limit"`
}

type PostLikeInput struct {
	PostID string `json:"postId"`
	UserID string `json:"userId"`
}

type UpdateBattlegroundRoomInput struct {
	TeamIds []string    `json:"teamIds"`
	Status  *RoomStatus `json:"status"`
}

type UpdateProfileInput struct {
	AvatarURL *string `json:"avatarUrl"`
	NameEng   *string `json:"nameEng"`
	NameChi   *string `json:"nameChi"`
	Bio       *string `json:"bio"`
}

type UpdateTeamInput struct {
	Name      *string    `json:"name"`
	AvatarURL *string    `json:"avatarUrl"`
	Points    *float64   `json:"points"`
	Powercard *Powercard `json:"powercard"`
}

type UpdateUserInput struct {
	TeamID  *string             `json:"teamId"`
	Profile *UpdateProfileInput `json:"profile"`
}

type UpsertDiscoveryInput struct {
	TeamID      string     `json:"teamId"`
	MissionID   string     `json:"missionId"`
	VideoURL    *string    `json:"videoUrl"`
	SubmittedAt *time.Time `json:"submittedAt"`
}

type UpsertEscapeInput struct {
	TeamID       string   `json:"teamId"`
	MissionOne   *bool    `json:"missionOne"`
	MissionTwo   *bool    `json:"missionTwo"`
	MissionThree *float64 `json:"missionThree"`
}

type UpsertHumanityInput struct {
	TeamID      string     `json:"teamId"`
	MissionID   string     `json:"missionId"`
	Batch       int        `json:"batch"`
	GatherLink  string     `json:"gatherLink"`
	Photo1      *string    `json:"photo1"`
	Photo2      *string    `json:"photo2"`
	Photo3      *string    `json:"photo3"`
	SubmittedAt *time.Time `json:"submittedAt"`
}

type UpsertSpeedInput struct {
	TeamID      string     `json:"teamId"`
	MissionID   string     `json:"missionId"`
	CompletedAt *time.Time `json:"completedAt"`
	Answer      *string    `json:"answer"`
}

type Gender string

const (
	GenderMale   Gender = "MALE"
	GenderFemale Gender = "FEMALE"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PastoralStatus string

const (
	PastoralStatusPastor PastoralStatus = "PASTOR"
	PastoralStatusScgl   PastoralStatus = "SCGL"
	PastoralStatusCgl    PastoralStatus = "CGL"
	PastoralStatusPcgl   PastoralStatus = "PCGL"
	PastoralStatusAcgl   PastoralStatus = "ACGL"
	PastoralStatusOm     PastoralStatus = "OM"
	PastoralStatusNb     PastoralStatus = "NB"
	PastoralStatusNf     PastoralStatus = "NF"
)

var AllPastoralStatus = []PastoralStatus{
	PastoralStatusPastor,
	PastoralStatusScgl,
	PastoralStatusCgl,
	PastoralStatusPcgl,
	PastoralStatusAcgl,
	PastoralStatusOm,
	PastoralStatusNb,
	PastoralStatusNf,
}

func (e PastoralStatus) IsValid() bool {
	switch e {
	case PastoralStatusPastor, PastoralStatusScgl, PastoralStatusCgl, PastoralStatusPcgl, PastoralStatusAcgl, PastoralStatusOm, PastoralStatusNb, PastoralStatusNf:
		return true
	}
	return false
}

func (e PastoralStatus) String() string {
	return string(e)
}

func (e *PastoralStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PastoralStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PastoralStatus", str)
	}
	return nil
}

func (e PastoralStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Powercard string

const (
	PowercardReverse       Powercard = "REVERSE"
	PowercardBlock         Powercard = "BLOCK"
	PowercardOnemorechance Powercard = "ONEMORECHANCE"
)

var AllPowercard = []Powercard{
	PowercardReverse,
	PowercardBlock,
	PowercardOnemorechance,
}

func (e Powercard) IsValid() bool {
	switch e {
	case PowercardReverse, PowercardBlock, PowercardOnemorechance:
		return true
	}
	return false
}

func (e Powercard) String() string {
	return string(e)
}

func (e *Powercard) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Powercard(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Powercard", str)
	}
	return nil
}

func (e Powercard) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RolePlayer        Role = "PLAYER"
	RoleTeamleader    Role = "TEAMLEADER"
	RoleClusterleader Role = "CLUSTERLEADER"
	RoleCrew          Role = "CREW"
)

var AllRole = []Role{
	RolePlayer,
	RoleTeamleader,
	RoleClusterleader,
	RoleCrew,
}

func (e Role) IsValid() bool {
	switch e {
	case RolePlayer, RoleTeamleader, RoleClusterleader, RoleCrew:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RoomStatus string

const (
	RoomStatusPreparing RoomStatus = "PREPARING"
	RoomStatusOngoing   RoomStatus = "ONGOING"
	RoomStatusEnded     RoomStatus = "ENDED"
)

var AllRoomStatus = []RoomStatus{
	RoomStatusPreparing,
	RoomStatusOngoing,
	RoomStatusEnded,
}

func (e RoomStatus) IsValid() bool {
	switch e {
	case RoomStatusPreparing, RoomStatusOngoing, RoomStatusEnded:
		return true
	}
	return false
}

func (e RoomStatus) String() string {
	return string(e)
}

func (e *RoomStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomStatus", str)
	}
	return nil
}

func (e RoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Satellite string

const (
	SatelliteFgasetapak Satellite = "FGASETAPAK"
	SatelliteFgarawang  Satellite = "FGARAWANG"
	SatelliteFgapuchong Satellite = "FGAPUCHONG"
	SatelliteFgapj      Satellite = "FGAPJ"
	SatelliteFgausj     Satellite = "FGAUSJ"
)

var AllSatellite = []Satellite{
	SatelliteFgasetapak,
	SatelliteFgarawang,
	SatelliteFgapuchong,
	SatelliteFgapj,
	SatelliteFgausj,
}

func (e Satellite) IsValid() bool {
	switch e {
	case SatelliteFgasetapak, SatelliteFgarawang, SatelliteFgapuchong, SatelliteFgapj, SatelliteFgausj:
		return true
	}
	return false
}

func (e Satellite) String() string {
	return string(e)
}

func (e *Satellite) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Satellite(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Satellite", str)
	}
	return nil
}

func (e Satellite) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
